# Generated by Django 4.2.6 on 2023-10-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name_plural': 'movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
